---
version: '3.7'
services:
  portainer_agent:
    image: portainer/agent
    env_file:
      - ./.env/portainer_agent.env
    deploy:
      mode: global
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    networks:
      - port_age-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  portainer:
    image: portainer/portainer
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
      placement:
        constraints: [node.role == manager]
    networks:
      - port-net
      - port_age-net
    volumes:
      - portainer:/data
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
  shepherd:
    image: mazzolino/shepherd
    env_file: 
      - ./.env/shepherd.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    networks:
      - port-net
      - plex-net
#      - pi-net
      - son-ng-net
      - rad-ng-net
      - jack-net
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
  qbittorrent:
    image: linuxserver/qbittorrent
    env_file:
      - ./.env/common.env
      - ./.env/qb.env
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    networks:
      - son-qb-net
      - rad-qb-net 
  smb:
    image: dperson/samba
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    env_file:
      - ./.env/common.env
    volumes:
      - downloads:/downloads
      - torrents:/torrents
    networks: 
      - smb-net
    ports:
      - "139:139"
      - "445:445"
      - "137-138:137-138/udp"
    command: -n -r -p -s "downloads;/downloads;yes;no" -s "torrents;/torrents;yes;no"
  plex:
    image: plexinc/pms-docker:public
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    volumes: 
      - downloads:/data
      - plex_transcode:/transcode
      - plex_config:/config
    networks:
      - plex-net
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "32410:32410/udp"
      - "32412-32414:32412-32414/udp"
      - "1900:1900/udp"
    env_file:
      - ./.env/common.env
      - ./.env/plex.env    
  sonarr:
    image: linuxserver/sonarr
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    env_file:
      - ./.env/common.env
    volumes:
      - sonarr:/config
      - downloads:/tv
      - downloads:/downloads
    networks:
      - son-qb-net
      - son-ng-net
      - son-jack-net
    ports:
      - "8989:8989"  
  radarr:
    image: linuxserver/radarr
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    env_file:
      - ./.env/common.env
    volumes:
      - radarr:/config
      - downloads:/movies
      - downloads:/downloads
    networks:
      - rad-qb-net
      - rad-ng-net
      - rad-jack-net
    ports:
      - "7878:7878"  
  jackett:
    image: linuxserver/jackett
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
      rollback_config:
        parallelism: 0
    env_file:
      - ./.env/common.env
    volumes:
      - jackett:/config
      - torrents:/downloads
    networks:
      - son-jack-net
      - rad-jack-net
      - jack-net  
#  pihole:
#    image: pihole/pihole:latest
# 
#    environment: 
#      - TZ=America/Toronto
#      - DNS1=208.67.220.222
#      - DNS2=208.67.222.220
#    volumes:
#      - pihole_config:/etc/pihole
#      - pihole_dnsmasq:/etc/dnsmasq.d
#    dns:
#      - 127.0.0.1
#    networks:
#      - pi-net
#    ports:
#      - "53:53"
#      - "53:53/udp"
#      - "67:67"
#      - "67:67/udp"

volumes:
  portainer:
  downloads:
  qbittorrent:
  torrents:
  plex_config:
  plex_transcode:
  sonarr:
  radarr:
  jackett:
#  pihole_config:
#  pihole_dnsmasq:

configs:
  nginx_config:
    file: ./nginx/homelab.conf
  netdata_nginx_config:
    file: ./netdata/nginx.conf
    
networks:
  port-net:
    driver: overlay
  watch-net:
    driver: overlay
  smb-net:
    driver: overlay
  plex-net:
    driver: overlay
  son-qb-net:
    driver: overlay
  son-ng-net:
    driver: overlay
  son-jack-net:
    driver: overlay
  rad-qb-net:
    driver: overlay
  rad-ng-net:
    driver: overlay
  rad-jack-net:
    driver: overlay
  jack-net:
    driver: overlay
  port_age-net:
    driver: overlay
#  pi-net:
#    driver: overlay
