---
version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    networks:
      - port-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    command: -H unix:///var/run/docker.sock
    restart: always

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    networks:
      - watch-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: always

  netdata:
    container_name: netdata
    image: titpetric/netdata
    cap_add:
      - SYS_PTRACE
    networks:
      - data-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./netdata:/etc/netdata/python.d
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - port-net
      - watch-net
      - data-net
      - qbit-net
      - smb-net
      - plex-net
    ports:
      #web
      - "80:80"
      - "443:443"
      #plex
      - "32400:32400"
    volumes:
      - ./nginx/homelab.conf:/etc/nginx/conf.d/homelab.conf
    depends_on: 
      - portainer
      - netdata
      - qbittorrent
      - smb
      - plex
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    networks:
      - qbit-net
    restart: always
  
  smb:
    image: dperson/samba
    container_name: smb
    environment:
      - TZ=EST5EDT
    volumes:
      - ./downloads:/downloads
    networks: 
      - smb-net
    ports:
      - "139:139"
      - "445:445"
      - "137-138:137-138/udp"
    command: -n -s "downloads;/downloads"
    restart: always

  plex:
    image: linuxserver/plex
    container_name: plex
    volumes: 
      - ./downloads:/data
      - ./plex/transcode:/transcode
      - ./plex/config:/config
    networks:
      - plex-net
    ports:
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    restart: always
    
networks:
  port-net:
    driver: bridge
  watch-net:
    driver: bridge
  data-net:
    driver: bridge
  qbit-net:
    driver: bridge
  smb-net:
    driver: bridge
  plex-net:
    driver: bridge
