---
version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    networks:
      - port-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    command: -H unix:///var/run/docker.sock
    restart: always

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    networks:
      - watch-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: always

  netdata:
    container_name: netdata
    image: titpetric/netdata
    cap_add:
      - SYS_PTRACE
    networks:
      - data-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./netdata:/etc/netdata/python.d
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - port-net
      - watch-net
      - data-net
      - qbit-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - portainer
      - netdata
      - qbittorrent 
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    networks:
      - qbit-net
    restart: always

networks:
  port-net:
    driver: bridge
  watch-net:
    driver: bridge
  data-net:
    driver: bridge
  qbit-net:
    driver: bridge
