apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-token: {{ .Values.cloudflareApiToken }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.email }}
    {{- if .Values.letsEncryptProduction }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end -}}
    privateKeySecretRef:
      name: cert-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.email }}
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-token
      selector:
        dnsNames:
        - "{{ .Values.domain }}"
        - "*.{{ .Values.domain }}"
