apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.letsEncrypt.email }}
    {{- if .Values.letsEncrypt.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end -}}
    privateKeySecretRef:
      name: cert-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: key
      selector:
        dnsNames:
        - "{{ .Values.domain }}"
        - "*.{{ .Values.domain }}"