{{- range $key, $value := .Values.apps }}
{{ if and $value.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
      - name: {{ $key }}
        image: {{ printf "%v:%v" $value.image.repository $value.image.tag }}
        imagePullPolicy: {{ $value.image.pullPolicy }}
        ports:
        - containerPort: {{ include (printf "homelab.%v.port" $key) . }}
      {{- if eq $key "oauth2-proxy" }}
        args:
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --whitelist-domain=.{{ $.Values.domain }}
        - --cookie-domain=.{{ $.Values.domain }}
        envFrom:
        - secretRef:
            name: {{ $key }}
      {{- end }}
      {{- if ne $key "oauth2-proxy" }}
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        {{- if eq $key "plex" }}
        - name: VERSION
          value: public
        {{- end }}
        volumeMounts:
        - name: {{ $key }}
          mountPath: /config
      volumes:
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $key }}
      {{- end }}
{{ end }}
{{ end }}