{{- range $key, $value := .Values.apps }}
{{ if and $value.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      containers:
      - name: {{ $key }}
        image: {{ printf "%v:%v" $value.image.repository $value.image.tag }}
        imagePullPolicy: {{ $value.image.pullPolicy }}
        ports:
        - containerPort: {{ include (printf "homelab.%v.port" $key) . }}
      {{- if eq $key "oauth2proxy" }}
        args:
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --whitelist-domain=.{{ $.Values.domain }}
        - --cookie-domain=.{{ $.Values.domain }}
        - --github-user="{{ join "," $value.users }}"
        envFrom:
        - secretRef:
            name: {{ $key }}
      {{- end }}
      {{- if ne $key "oauth2proxy" }}
        env:
        - name: PUID
          value: "{{ $.Values.uid }}"
        - name: GUID
          value: "{{ $.Values.gid }}"
        {{- if eq $key "plex" }}
        - name: VERSION
          value: public
        {{- end }}
        volumeMounts:
        - name: {{ $key }}
          mountPath: /config
        {{- if and $.Values.mediaPersistence.enabled (and (ne $key "plex" ) (ne $key "jackett") (ne $key "oauth2proxy")) }}
        - name: {{ $key }}-media
          mountPath: /downloads
        {{- end }}
        {{- if or (eq $key "radarr") (eq $key "plex") }}
        - name: {{ $key }}-media
          mountPath: /movies
        {{- end }}
        {{- if or (eq $key "sonarr" ) (eq $key "plex")}}
        - name: {{ $key }}-media
          mountPath: /tv
        {{- end }}
      volumes:
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $key }}
      {{- if and $.Values.mediaPersistence.enabled (and (ne $key "jackett") (ne $key "oauth2proxy")) }}
      - name: {{ $key }}-media
      {{- if eq $.Values.mediaPersistence.type "nfs" }}
        nfs:
          server: {{ $.Values.mediaPersistence.nfs.server }}
          path: {{ $.Values.mediaPersistence.nfs.path }}
      {{- end }}
      {{- if eq $.Values.mediaPersistence.type "hostPath" }}
        hostPath:
          path: {{ $.Values.mediaPersistence.hostPath }}
          type: DirectoryOrCreate
      initContainers:
      - name: hostpath-permission-changer
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /tmp/hostpath; chown -R {{ $.Values.uid }}:{{ $.Values.gid }} /tmp/hostpath"]
        volumeMounts:
        - name: {{ $key }}-media
          mountPath: /tmp/hostpath
      {{- end }}
      {{- if eq $.Values.mediaPersistence.type "pvc" }}
        persistentVolumeClaim:
          claimName: shared-media
      {{- end }}
      {{- end }}
      {{- end }}
{{ end }}
{{ end }}