{{- range $key, $value := .Values.apps }}
{{ if $value.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      volumes:
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $key }}
      containers:
      - name: {{ $key }}
        image: {{ printf "%v:%v" $value.image.repository $value.image.tag }}
        imagePullPolicy: {{ $value.image.pullPolicy }}
        ports:
        - containerPort: {{ include (printf "homelab.%v.port" $key) . }}
        volumeMounts:
        - name: {{ $key }}
          mountPath: /config
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        {{- if eq $key "plex" }}
        - name: VERSION
          value: public
        {{- end }}
{{ end }}
{{ end }}