{{- range $key, $value := .Values.apps }}
{{ if $.Values.apps.qbittorrent.enabled }} # qbittorrent must be enabled for init
{{ if $value.enabled }}
{{ if or (eq $key "sonarr") (eq $key "radarr") (eq $key "qbittorrent")}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%v-init-secret" $key }}
type: Opaque
stringData:
{{- if eq $key "qbittorrent" }}
  username: {{ $value.username }}
  password: {{ $value.password }}
{{- end }}
{{- if or (eq $key "sonarr") (eq $key "radarr") }}
  downloadClients.csv: |
    Id,Enable,Name,Implementation,Settings,ConfigContract,Priority
    1,1,qbittorrent,QBittorrent,"{
      ""host"": ""qbittorrent"",
      ""port"": 8080,
      ""useSsl"": false,
      ""username"": ""{{ $.Values.apps.qbittorrent.username }}"",
      ""password"": ""{{ $.Values.apps.qbittorrent.password }}"",
      {{- if eq $key "sonarr" }}
      ""tvCategory"": ""{{ $key }}"",
      ""recentTvPriority"": 0,
      ""olderTvPriority"": 0,
      {{- else }}
      ""movieCategory"": ""{{ $key }}"",
      ""recentMoviePriority"": 0,
      ""olderMoviePriority"": 0,
      {{- end }}
      ""initialState"": 0
    }",QBittorrentSettings,1
{{- end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}