{{- range $key, $value := .Values.apps }}
{{ if $.Values.apps.qbittorrent.enabled }} # qbittorrent must be enabled for init
{{ if $value.enabled }}
{{ if or (eq $key "sonarr") (eq $key "radarr") (eq $key "qbittorrent")}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%v-init" $key }}
data:
  init.sh: |
    #!/bin/bash
    set -euo pipefail

    {{- if or (eq $key "sonarr") (eq $key "radarr") }}
    while [ ! -f /config/{{ $key }}.db ]; do
      echo "Waiting for {{ $key }} database to exist..."
      sleep 1;
    done;
    echo "Database found!"
    echo "Adding download client..."
    sqlite3 -csv /config/{{ $key }}.db '.import /tmp/init-secret/downloadClients.csv DownloadClients'
    {{- end }}

    {{- if eq $key "qbittorrent" }}
    until [ $(curl -sw '%{http_code}' -o /dev/null "http://qbittorrent:8080/api/v2/auth/login?username=admin&password=adminadmin") == "200" ]; do
      echo "Waiting for {{ $key }} API...";
      sleep 1;
    done;
    echo "API is ready!"
    echo "Changing settings..."
    curl -so /dev/null -c cookies "http://qbittorrent:8080/api/v2/auth/login?username=admin&password=adminadmin"
    curl -so /dev/null -c cookies -b cookies "http://qbittorrent:8080/api/v2/app/setPreferences?json=\{\"web_ui_username\":\"${WEB_UI_USERNAME}\",\"web_ui_password\":\"${WEB_UI_PASSWORD}\"\}"
    {{- end}}
{{ end }}
{{ end }}
{{ end }}
{{ end }}