#{{- if .Values.mediaPersistence.enabled }}
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: {{ .Values.mediaPersistence.type }}-mount
#spec:
#  accessModes: [ReadWriteMany]
#  {{- if eq .Values.mediaPersistence.type "nfs" }}
#  nfs:
#    server: {{ .Values.mediaPersistence.nfs.server }}
#    path: {{ .Values.mediaPersistence.nfs.path }}
#  {{- end }}
#{{- end }}