{{- range $key, $value := .Values.apps }}
{{ if and $value.enabled (ne $key "oauth2proxy") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.configPersistence.size }}
{{ end }}
{{ end }}
{{- if and (.Values.mediaPersistence.enabled) (eq .Values.mediaPersistence.type "pvc") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media
spec:
  {{- if .Values.mediaPersistence.pvc.storageClass }}
  storageClass: {{ .Values.mediaPersistence.pvc.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.mediaPersistence.pvc.mode }}
  resources:
    requests:
      storage: {{ .Values.mediaPersistence.pvc.size }}
{{- end }}