{{- range $key, $value := .Values.apps }}
{{ if and $value.enabled (ne $key "oauth2-proxy") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.configPersistence.size }}
{{ end }}
{{ end }}