apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  key: {{ .Values.cloudflare.apiKey }}
{{- if .Values.apps.qbittorrent.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent
type: Opaque
stringData:
  username: {{ .Values.apps.qbittorrent.username }}
  password: {{ .Values.apps.qbittorrent.password }}
{{- end }}