apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  key: {{ .Values.cloudflare.apiKey }}
{{- if .Values.apps.oauth2Proxy.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2Proxy
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.apps.oauth2Proxy.secret.clientID }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.apps.oauth2Proxy.secret.clientSecret }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ randAlphaNum 32 }}
{{- end }}