apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  key: {{ .Values.cloudflare.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.oauth2.clientID }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oauth2.clientSecret }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.oauth2.cookieSecret }}