{{- range $key, $value := .Values.apps }}
{{ if $value.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
spec:
  selector:
    app: {{ $key }}
  ports:
  - name: {{ $key }}
    port: {{ include (printf "homelab.%v.port" $key) . }}
{{ end }}
{{ end }}