{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ .name }}
    template:
      metadata:
        labels:
          app: {{ .name }}
      spec:
        containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
          - containerPort: {{ .port }}
        {{- if .env }}
          env:
        {{- range $key, $val := .env }}
          - name: {{ $key }}
            value: {{ $val }}
        {{ end -}}
        {{ end -}}
{{ end -}}